FROM ubuntu:26.04

ARG USERNAME=developer
ARG USER_UID=1000
ARG USER_GID=1000

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    gdb \
    git \
    just \
    clang \
    clang-format \
    clang-tidy \
    ccache \
    neovim \
    libboost-all-dev \
    && rm -rf /var/lib/apt/lists/*

# Remove gcc-16 because clang will select gcc-16 but fail to find libstdc++ 
# since there is no g++-16
RUN apt-get remove -y \
    gcc-16-x86-64-linux-gnu \
    gcc-16 \
    libgcc-16-dev \
    libgfortran-16-dev \
    gfortran-16-x86-64-linux-gnu

RUN apt-get autoremove -y

RUN if id -u ${USERNAME} >/dev/null 2>&1; then \
        echo "User exists"; \
    elif id -u ${USER_UID} >/dev/null 2>&1; then \
        existing_user=$(getent passwd ${USER_UID} | cut -d: -f1); \
        usermod --login ${USERNAME} ${existing_user}; \
        groupmod --new-name ${USERNAME} $(getent group ${USER_GID} | cut -d: -f1); \
        usermod --home /home/${USERNAME} --move-home ${USERNAME}; \
    else \
        groupadd --gid ${USER_GID} ${USERNAME}; \
        useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME}; \
    fi

USER $USERNAME

RUN mkdir -p /home/developer/.ccache
RUN ccache --set-config max_size=10G

ENV CC=clang
ENV CXX=clang++

WORKDIR /workspace
