FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    gdb \
    git \
    just \
    clang \
    clang-format \
    clang-tidy \
    ccache \
    neovim \
    && rm -rf /var/lib/apt/lists/*

RUN ccache --set-config max_size=10G

WORKDIR /workspace

CMD ["/bin/bash"]
